### ISSUE TITLE
Typo on Koopa the Quick Victory

### ISSUE THREAD

**Issue by andrewfx24** [BWGLite/super-spamton-64#2]
Very fun hack, but I want to point this out in case it hasn't been brought to your attention yet. I assume it's supposed to be "just a blur" on the first image and "tortoise" on the second? Using Project64 in case it's a text bug or something.
![image](https://user-images.githubusercontent.com/42969940/196240357-5fce7ab8-c215-4085-876d-9e343fa0dffd.png)
![image](https://user-images.githubusercontent.com/42969940/196241106-54b27d03-20c4-4e95-8fdc-a6da01f30df6.png)

**Comment by suburbGira** [comment]
feels to me like "Tortise" could be a spamton thing, like how he misspells special as specil

**Comment by Rudxain** [comment]
> "It's not a bug, it's a feature"
